# -*- coding: utf-8 -*-
"""four_digits.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdj1fihR8eIpPbybTfZ2P1TvPSZGcome
"""

#CS175
#Lucas Vandenakker
#four_digits

userInput = int(input("Enter a four digit number: "))

if (len(str(userInput)) != 4):
    print("Your input was not four digits. Quitting.")
    exit()


digit1 = int(userInput / 1000) %10
digit2 = int(userInput / 100) % 10
digit3 = int(userInput / 10) % 10
digit4 = userInput % 10

sum = digit1 + digit2 + digit3 + digit4
print(f"The individual dights of your input are : {digit1}, {digit2}, {digit3}, {digit4}")
print("The sum of your input is", sum)

