# -*- coding: utf-8 -*-
"""lockerCombo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlpTA90Q9fk7UVoRPBOQ7dW3NteBUa0U
"""

#CS-175
#Lucas Vadneakker
#lockerCombo

import random


def lockerCombo():
  myName = "Lucas Vandenakker"
  num1 = random.randint(0,39)
  num2 = random.randint(0,39)
  num3 = random.randint(0,39)

  while(num1 == num2 or num1 == num3 or num2 == num3):
    print(f"The locker combination is {num1}-{num2}-{num3}")
    print("\tGenerating numbers again, this is not a valid combination")
    num1 = random.randint(0,39)
    num2 = random.randint(0,39)
    num3 = random.randint(0,39)

  print(f"The locker combination is {num1}-{num2}-{num3}")
  print("\tThis combination will work!")

lockerCombo()