# -*- coding: utf-8 -*-
"""restuarant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlpTA90Q9fk7UVoRPBOQ7dW3NteBUa0U
"""

#CS-175
#Lucas Vadneakker
#restaurant

vegTorF = False #True or False
veganTorF = False #True or False
gFTorF = False #True or False

veg = input("Is anyone in your party vegetarian?") #vegetarian
if (veg.casefold() == "yes".casefold()):
    vegTorF = True

vegan = input("Is anyone in your party vegan?") #vegan
if (vegan.casefold() == "yes".casefold()):
    veganTorF = True
gF = input("Is anyone in your party gluten-free?") #Gluten Free
if (gF.casefold() == "yes".casefold()):
    gFTorF = True

print("Here are your restaruant choices: ")

if(vegTorF == False and veganTorF==False and gFTorF==False):
  print("Joe’s Gourmet Burgers ")

elif(veganTorF == False and gFTorF == False):
  print("Mamas Fine Italian")

elif(veganTorF == False):
  print("Main Street Pizza")

print("Corner Cafe")
print("Chefs Kitchen")